[project]
name = "news-server"
version = "0.0.1"
description = "News MCP server (stub)"
readme = "README.md"
requires-python = ">=3.10"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

