[package]
name = "foreman-policy"
version = "0.0.1"
edition = "2021"

[lib]
name = "foreman_policy"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"

