[package]
name = "foreman-telemetry"
version = "0.0.1"
edition = "2021"

[dependencies]
once_cell = "1"
prometheus = "0.13"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt", "json"] }

