name: Lint

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Rust fmt
        run: cargo fmt --all -- --check
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install python linters
        run: |
          python -m pip install --upgrade pip
          pip install ruff black
      - name: Ruff
        run: ruff . || true
      - name: Black check
        run: black --check . || true

